# Default configuration for "SvcUtilBundle"
svc_util:
    contact_form:

        # Email adress for contact mails
        contact_mail:         dev@sv-systems.com

        # Which route should by called after amil sent
        route_after_send:     index

        # Enable captcha for contact form?
        enable_captcha:       false

        # Enable sending a copy of the contact request to me too?
        enable_copy_to_me:    true

    mailer:

        # Default sender mail address
        mail_address:         dev@sv-systems.com

        # Default sender name
        mail_name:            'Test User'